### ISSUE TITLE
Suggestion: Help user know where in the website they are

### ISSUE THREAD

**Issue by gevhaz** [sakiadachi/hatsuon-app#3]
I like the design of the app! But as a new user, I sometimes have trouble knowing where in the app I am. For example, in the 'list of collections' view, just the names of the collections are listed:

![image](https://github.com/user-attachments/assets/b67c3558-1d6f-4fd1-9e7b-73121be0b71b)

I think it could help new users if the page had some sort of title like "Decks:".

Similarly, the page contains an "Add" button, but perhaps "Add deck" would be more clear. Same when adding new words:

![image](https://github.com/user-attachments/assets/396f09a9-6676-4dd4-b939-ed37a53a0783)

Will the 'Add' button add a word or a phrase?

**Comment by sakiadachi** [comment]
Hey, @gevhaz !
Thank you for making the issue.
Can I get your feedback in the chages below?

- Added page title in each page
- Button Label "Add" -> "Add Collection" / "Add Phrase"

![Screenshot 2024-08-27 at 10-05-11 Home](https://github.com/user-attachments/assets/b5fd5fc3-20b4-4b9e-8e6b-7fab72b333dd)
![Screenshot 2024-08-27 at 10-08-39 Collection](https://github.com/user-attachments/assets/d65a4b18-16ec-429a-8a11-86d1755c92c2)

**Comment by gevhaz** [comment]
Great, I think this is much clearer. Feel free to close the issue.

A separate but somewhat related thing is the breadcrumb trail 'Home / German'. It feels like it's missing one level, like 'Home / Collections / German'.

**Comment by sakiadachi** [comment]
Yay thanks!

Actually, home link goes to Collections page :o 
Do you think instead of "Home", "Collections" is good?
"Collections / German / Phrase name "

Also I will search how to add you as a contributor of this repository ! ( never done it before)

**Comment by gevhaz** [comment]
Yeah, that would make sense :)

I think you get added as a contributor when you have gotten a commit that you are the author of merged to the repository, so I probably have to make some actual code contributions for that to happen :grin:

**Comment by sakiadachi** [comment]
I just released #3 and #4 to the production, take a look when you have time!

oh that's right..! I can't control that in my repository haha
any contribution is welcome :)
